name: Make Kitemaker Ticket

on:
    workflow_dispatch:
        inputs:
            title:
                required: true
                type: string
            body:
                required: true
                type: string
            repo_name:
                required: true
                type: string
    workflow_call:
        inputs:
            title:
                required: true
                type: string
            body:
                required: true
                type: string
            repo_name:
                required: true
                type: string

env:
    X-API-KEY: ${{ secrets.KITEMAKER_X_API_KEY }}
    SPACE_ID: ${{ secrets.KITEMAKER_SPACE_ID }}
    STATUS_ID: ${{ secrets.KITEMAKER_STATUS_ID }}


jobs:
    make-ticket:
        runs-on: ubuntu-latest
        steps:
            - name: Make Ticket
              run: |
                
                echo " The body details are : ${{ toJson(env.DATA) }}"
                curl  -H "Content-Type: application/json"  -H "X-API-KEY: ${{ env.X-API-KEY }}" --data-raw '${{ toJson(env.DATA) }}' "https://toil.kitemaker.co/developers/rest/v1/workitem"
              env:
                BODY: ${{ inputs.body }}
                DATA: '{"spaceId": "${{ env.SPACE_ID }}", "statusId": "${{ env.STATUS_ID }}", "title": "From ${{ inputs.repo_name }} -- ${{ inputs.title }}", "description": "${{ inputs.body }}"}'
