name: Make Kitemaker Ticket

on:
    workflow_dispatch:
        inputs:
            title:
                required: true
                type: string
            body:
                required: true
                type: string
            repo_name:
                required: true
                type: string
    workflow_call:
        inputs:
            title:
                required: true
                type: string
            body:
                required: true
                type: string
            repo_name:
                required: true
                type: string
            
# env:
#     X-API-KEY: ${{ secrets.KITEMAKER_X_API_KEY }}
#     SPACE_ID: ${{ secrets.KITEMAKER_SPACE_ID }}
#     STATUS_ID: ${{ secrets.KITEMAKER_STATUS_ID }}
#     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


# jobs:
#     make-ticket:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Make Ticket
#               id: apicall
#               run: |
                
#                 echo " The body details are : ${{ toJson(inputs.body) }}" | tr -d "<>" | tr \' \\\' 
#                 RESPONSE=$(curl  -H "Content-Type: application/json"  -H "X-API-KEY: ${{ env.X-API-KEY }}" --data-raw '{"spaceId": "${{ env.SPACE_ID }}", "statusId": "${{ env.STATUS_ID }}", "title": "From ${{ inputs.repo_name }} -- ${{ inputs.title }}", "description": ${{ toJson(inputs.body) }}}' "https://toil.kitemaker.co/developers/rest/v1/workitem")
#                 echo "$RESPONSE"
#                 TICKET_NUMBER=$(echo $RESPONSE | jq -r '.number')
#                 echo "TICKET_NUMBER=$TICKET_NUMBER" >> $GITHUB_ENV
#               env:
#                 BODY: ${{ inputs.body }}
            





env:
  X-API-KEY: ${{ secrets.KITEMAKER_X_API_KEY }}
  SPACE_ID: ${{ secrets.KITEMAKER_SPACE_ID }}
  STATUS_ID: ${{ secrets.KITEMAKER_STATUS_ID }}

jobs:
  make-ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment variables
        run: |
          echo "TITLE='${{ inputs.title }}'" >> $GITHUB_ENV
          echo "BODY='${{ inputs.body }}'" >> $GITHUB_ENV
          echo "REPO_NAME='${{ inputs.repo_name }}'" >> $GITHUB_ENV

      - name: Make Kitemaker Ticket API Call
        run: |
          TITLE="$TITLE"
          BODY="$BODY"
          REPO_NAME="$REPO_NAME"

          echo "TITLE: $TITLE"
          echo "BODY: $BODY"
          echo "REPO_NAME: $REPO_NAME"

          # Construct JSON payload with multiline BODY
          PAYLOAD=$(cat <<EOF
          {
            "spaceId": "${{ env.SPACE_ID }}",
            "statusId": "${{ env.STATUS_ID }}",
            "title": "From $REPO_NAME -- $TITLE",
            "description": "$BODY"
          }
          EOF
          )

          echo "Payload:"
          echo "$PAYLOAD"

          # Make the API call
          RESPONSE=$(curl -s -H "Content-Type: application/json" -H "X-API-KEY: ${{ env.X-API-KEY }}" --data "$PAYLOAD" "https://toil.kitemaker.co/developers/rest/v1/workitem")

          echo "API Response:"
          echo "$RESPONSE"

          # Extract the ticket number from the response if needed
          TICKET_NUMBER=$(echo "$RESPONSE" | jq -r '.number')
          echo "TICKET_NUMBER=$TICKET_NUMBER" >> $GITHUB_ENV
