name: Release Netclient

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:

  release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: LiuChen001/netclient
          ref: develop
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Setup git
        run: |
          git config --global user.name "LiuChen"
          git config --global user.email "354633839@qq.com"
      - name: Create Release Branch
        run: |
          git switch -c release-${{ inputs.version }}
      - name: Fix go mod
        run: |
          go get github.com/LiuChen001/netmaker@${{ inputs.version }}
          go mod tidy
          git commit -am 'update go mod for release'
      - name: Update Release Branch
        run: |
          git tag -f ${{ inputs.version }}
          git push origin release-${{ inputs.version }}
          git push origin ${{ inputs.version }}

  release-assets:
    needs: release-branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: LiuChen001/netclient
          ref: release-${{ inputs.version }}
          fetch-depth: 0
      - name: Get Tags
        run: |
          git fetch --force --tags
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean --release-notes release.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    needs: release-branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: LiuChen001/netclient
          ref: release-${{ inputs.version }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64, linux/arm/v7
          push: true
          tags: |
            liuchen002/netclient:${{ inputs.version }}
            liuchen002/netclient:latest
