name: Release Netmaker
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:

  release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: LiuChen001/netmaker
          ref: develop
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Setup git
        run: |
          git config --global user.name "LiuChen"
          git config --global user.email "354633839@qq.com"
      - name: Create Release Branch
        run: |
          git switch -c release-${{ inputs.version }}
          git tag -f ${{ inputs.version }}
          git push origin release-${{ inputs.version }}
          git push origin ${{ inputs.version }}

  release-assets:
    needs: release-branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: LiuChen001/netmaker
          ref: release-${{ inputs.version }}
          fetch-depth: 0
      - name: Get Tags
        run: |
          git fetch --force --tags
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean --release-notes release.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  packages:
    needs: release-branch
    runs-on: ubuntu-latest
    steps:
      - name: setup ssh
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_devops
          chmod 600 ~/.ssh/id_devops
          cat >>~/.ssh/config <<END
          Host *.clustercat.com
            User root
            IdentityFile ~/.ssh/id_devops
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.TESTING_SSH_KEY }}
      - name: set version
        run: |
            VERSION=$(echo ${{ inputs.version }} | tr -cd '[:digit:].')
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
            echo ${VERSION}
      - name: apt/rpm
        run: |
          ssh fileserver.clustercat.com "cd packages/nmctl; export VERSION=${VERSION}; export REVISION=0; ./buildall.sh" 
