name: Integration Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
      - name: Build
        run: |
          go version
          CGO_ENABLED=0 go build -c src/updateNetwork -v  . 
          CGO_ENABLED=0 go build -c test -v  . 
          CGO_ENABLED=0 go build -c upgrade -v  . 
  
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
      - name: run tests
        run: |
          go vet ./...
          go test ./... -v
          golangci-lint run
