name: 'Update Network'

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    name: Update Test Network
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/id_devops
        chmod 600 ~/.ssh/id_devops 
        cat >>~/.ssh/config <<END
        Host *.clustercat.com
          User root
          IdentityFile ~/.ssh/id_devops
          StrictHostKeyChecking no
        END
      env:
          SSH_KEY: ${{ secrets.TESTING_SSH_KEY }}
    - name: Update Network
      uses: ./.github/actions/update-test-network
      env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN }}
