name: Update Demo Server

on:
    workflow_call:
        inputs:
            version:
                required: true
                type: string
    workflow_dispatch:
        inputs:
            version:
                required: true
                type: string



jobs:
    update-demo-environment:
        runs-on: ubuntu-latest
        steps:
        - name: setup ssh
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.TESTING_SSH_KEY }}" > ~/.ssh/id_devops
            chmod 600 ~/.ssh/id_devops
            cat >> ~/.ssh/config <<EOF
            Host *.clustercat.com
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
            IdentityFile ~/.ssh/id_devops
            EOF
          env:
            TESTING_SSH_KEY: ${{ secrets.TESTING_SSH_KEY }}
        - name: update server
          run: | 
                ssh root@206.81.15.201 "bash updateimage.sh ${{ inputs.version }}"
          